[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#007BFF"
secondaryBackgroundColor = "#6C757D"
backgroundColor = "#F8F9FA"
textColor = "#212529"
font = "IBM Plex Sans"
